# Generated by Django 6.0.6 on 2026-07-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
